
clustering_framework: cc
project_name: PB_scope
group: PB_scope
run_name: CC
dataset: PB_scope
num_workers: 4
gpu: 0
seed: 0
dataset_path: "/home/drugdataset_final/dataset_t6"
output_dir: "/home/drug_model/model/T6"
mixed_precision: True
backbone: resnet34
proj_dim: 64
optimizer: adam
lr: 0.0001
weight_decay: 0
lr_schedule: cosine
epochs: 200
eval_interval: 10
crop_size: 224
batch_size: 128

clusters: 15